### ISSUE TITLE
The lives counter works outside of Infinite Mode

### ISSUE THREAD

**Issue by ItsJaid** [decoder0007/Infinite-Mode#1]
when playing levels outside of infinite mode, i still have the lives counter. it's also functional, as when I hit 0 lives it kicks me out of the level i'm playing.

here's a video of it: https://user-images.githubusercontent.com/103144388/162060511-e2897a55-2f29-4cda-bbae-04f769994b9e.mp4

**Comment by Decoder0007** [comment]
Yeah I thought that might happen. Just move it to a different folder or
disable it when you aren’t using it

**Comment by ItsJaid** [comment]
a'ight. will you fix it at some point or no?

**Comment by Decoder0007** [comment]
Yeah I’ll do it at some point
