### ISSUE TITLE
(Suggestion) Difficulty should change more often

### ISSUE THREAD

**Issue by DeepResonanceX** [decoder0007/Infinite-Mode#2]
Idk if it's a bug for me but it's only after playing like 5 Easy difficulty levels that i get to move onto Normal difficulty levels. It gets a little tedious and honestly it'd probably be better if it changed every 2 levels or just every level u play, to make it a little more fun.

Cool mod tho, love the idea

**Comment by Decoder0007** [comment]
The difficulty increases every five levels. It gives you a chance to make some lives before the difficulty gets too hard! (It used to be ten)

**Comment by DeepResonanceX** [comment]
oh lol yea 10 is probs a little too much, i understand, tho idk i'd probably just like for it to be a little more challenging, maybe if still plan on updating this, some more difficulty options with less levels per difficulty could be a cool idea?

**Comment by Decoder0007** [comment]
I’ll add a slider or I put box for levels per difficulty
